version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - url-shortener-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER:-user}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
      MONGO_DATABASE: ${MONGO_DATABASE:-urls}
    restart: unless-stopped

  mongodb:
    container_name: url-shortener-database
    image: mongo:8.0.15-noble
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
    networks:
      - url-shortener-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  mongodb_data:
    driver: local

networks:
  url-shortener-network:
    name: url-shortener-network
    driver: bridge