version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - url-shortener-network
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}

  mongodb:
    container_name: mongodb-url-shortener
    image: mongo:8.0.15-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - url-shortener-network
    volumes:
      - mongoData:/data/db

volumes:
  mongoData:
    driver: local

networks:
  url-shortener-network:
    name: url-shortener-network
    driver: bridge